temporalio/api-go

serviceerror/convert.go

Fix for when details are not specified - See this test in SDK https://github.com/temporalio/temporal-go-sdk/blob/v0.22.0/internal/grpc_dialer_test.go#L39

Return empty NotFound when Details/Failure is nil

---

serviceerror/convert.go

This prevents `context.Canceled` to be converted to gRPC status with `codes.Unknown` and use proper `codes.Canceled` instead.

Add custom convertion for context.Canceled error

---

serviceerror/alreadyExists.go
serviceerror/convert.go

Add a basic AlreadyExists Service Error
**Why?**
I want to return a descriptive code from the operator API in case the entity attempted to register already exists. Currently, we use INVALID_ARGUMENT and it's not technically correct and hard to be parsed by the clients.
See https://github.com/temporalio/api/pull/161

Add AlreadyExists Failure

---

LICENSE
go.mod
go.sum
serviceerror/convert.go
serviceerror/convert_test.go
serviceerror/failed_precondition.go

Don't return `InvalidArgument` if error details are of unknown type.
**Why?**
Previously if new error details type is added then `InvalidArgument` was returned no matter of actual status code. This is because `extractErrorDetails` returned and error and this [error](https://github.com/temporalio/gogo-protobuf/blob/master/types/any.go#L96) was treated as fatal. This made adding new error details very inconvenient. With thss PR, in case of unknown error details type (and any other deserialization error), `serviceerror` will be built based on status code only which is more reasonable.
New unit tests.
Some weird deserialization errors will be swallowed.

Don't return InvalidArgument if error details are of unknown type

---

.github/CODEOWNERS
Makefile

Treat protoc warnings as errors.
**Why?**
Proto files should not have any warnings.
`make proto`
No risks, but requires `protoc` version [3.16.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.16.0) or higher.

Treat protoc warnings as errors

---

Makefile

Add gogoslick mapping for Google's any.proto
**Why?**
Required to use the Any type. Use of Google version of this type fails to compile because gogo expects certain member functions.
Compile upstream api that has been modified to include an Any field.
Low - this mapping is currently unused but will be used shortly.

Add gogoslick mapping for Google's any.proto

---

.github/workflows/ci.yml
Makefile

Run `go mod tidy` before running the proxy codegen
**Why?**
The unpinned versions (e.g. we depend on the latest version of google.golang.org/genproto) change frequently and if the go.sum isn't updated, builds will fail.
Running locally

Update go.sum before building proxygen

---

.github/workflows/ci.yml

Replace interpolated github context variables with default variables used more defensively. 
**Why?**
This mitigates an attacker naming a branch a command that could run in our runner's context.
Ran in my own fork and it was fine in my workflow.
Somehow not printing the build info in the workflow output.

Mitigate injection

---

.github/workflows/update-proto.yml

Fix Go setup step in update-proto workflow.
**Why?**
YAML interprets `1.20` as `1.2` and this workflow broke.
I actually didn't. But we know this works from https://github.com/temporalio/api-go/blob/224b196919eabc405c43051c9f280afb6457e5ba/.github/workflows/ci.yml#L17
Workflow still broken after this.

Fix update-proto workflow

---

go.mod

I've marked version 1.26.1 as [retracted](https://go.dev/ref/mod#go-mod-file-retract) so that `go get -u` will not longer upgrade to it. It will still be available if you manually specify it, meaning our downstream repos require no changes.
**Why?**
This was released before we were entirely ready and it caused some user development workflows to break
N/A

Retract version 1.26.1

---

go.mod

We need to retract `v1.26.1`, to do that we need to publish `v1.26.2` to make Go tooling aware of the retraction. We also then need to retract the version published to make the retraction `v1.26.2` this is valid.
```
A version containing retractions may retract itself. If the highest release or pre-release version of a module retracts itself, the @latest query resolves to a lower version after retracted versions are excluded.
```
https://go.dev/ref/mod#go-mod-file-retract

Preemptively retract v1.26.2

---

serviceerror/convert.go
serviceerror/convert_test.go

Make `Convert` handle wrapped `ServiceError`s
**Why?**
We shouldn't lose any more specific error info (i.e. grpc code) if it's present at all in the error.
unit test
This code path is a little more expensive, if we end up using it a lot of the time that's a slight waste.

Handle wrapped ServiceErrors in Convert

---

Makefile

It enables file-based submodule updates, regardless of the user-defined setting.
The idea for the fix was found here: https://bugs.launchpad.net/ubuntu/+source/git/+bug/1993586/comments/3
There is an option to set this globally, but that's undesirable. 
**Why?**
Without this, it fails for me with:
```
fatal: transport 'file' not allowed
fatal: Unable to fetch in submodule path 'proto/api'
```
Ran `make proto` locally. Only succeeds with the change.
I wouldn't expect older git versions to break but to ignore the config.

allow git submodule update

---

.gitignore

Ignores the file `.go-helpers-installed` from git.
**Why?**
The file seems to be created as part of the Make target `go-grpc`:
```
go-grpc: clean .go-helpers-installed $(PROTO_OUT)
```
But gets in the way when switching branches.
`git status` doesn't show the file anymore.
N/A

ignore .go-helpers-installed

---

common/v1/payload_json.go
internal/temporalcommonv1/payload_json.go
internal/temporalcommonv1/payload_json_test.go

1. Map values may not be singular items but full values
2. Empty maps should be marshalled as `{}`, not `null`
This fixes temporalio/api#349
**Why?**
Empty maps should always have been marshalled as empty objects, this was a bug in our code. While here I realized a deeper bug, where maps would only support simple values (strings, numbers, etc) but not embedded maps, lists, etc.
New unit test
None

Fix marshalling of shorthand maps

---

cmd/protogen/disable_utf8.go
cmd/protogen/main.go

Disable utf8 validation on all string fields.
**Why?**
We migrated from gogoproto to the official Go proto compiler and runtime library. Gogo did not enforce valid utf8 in string fields. To ease the transition, we need the official proto library to relax enforcement of utf8 until we can verify it won't break things.
Tested manually with invalid utf8 data.

Disable utf-8 validation on strings

---

.github/workflows/update-proto.yml

See description
**Why?**
Actions should have been failing due to lack of permissions to push to master.
I ran the changes in a shell script that confirms the behavior.

Only pass action if commit fails, fail if push fails

---

internal/protojson/json/decode.go
internal/protojson/json/decode_test.go
internal/protojson/json_unmarshal_test.go
internal/protojson/well_known_types.go

Official description from NVD: https://nvd.nist.gov/vuln/detail/CVE-2024-24786
From the official commit:
> encoding/protojson, internal/encoding/json: handle missing object values
>
> In internal/encoding/json, report an error when encountering a }
> when we are expecting an object field value. For example, the input
> `{"":}` now correctly results in an error at the closing } token.
>
> In encoding/protojson, check for an unexpected EOF token in
> skipJSONValue. This is redundant with the check in internal/encoding/json,
> but adds a bit more defense against any other similar bugs that
> might exist.
>
> Fixes CVE-2024-24786
>
> Change-Id: I03d52512acb5091c8549e31ca74541d57e56c99d
> Reviewed-on: https://go-review.googlesource.com/c/protobuf/+/569356
> TryBot-Bypass: Damien Neil …

Port fix for CVE-2024-24786

---

common/v1/payload_json.go
internal/temporalcommonv1/payload_json.go
internal/temporalcommonv1/payload_json_test.go

Marshal/unmarshal empty `Payloads` as `[]` in shorthand encoding (also accept `null` on unmarshal).
Handle the case where one or more `Payload` within `Payloads` can't be encoded as shorthand.
**Why?**
These cases were producing invalid json.
unit tests

Fix shorthand encoding of Payloads

---

common/v1/payload_json.go
internal/temporalcommonv1/payload_json.go
internal/temporalcommonv1/payload_json_test.go

I fixed an embarrassing bug in shorthand payload marshaling when `null` is present
**Why?**
Because it was a bug!
I added a new test. I plan to add property-based testing to this shortly, but that will come in a new PR.
None

Fix shorthand payload marshaling when `null` is present

---

cmd/protogen/main.go

Pass through the `--descriptor_set_in` flag to protoc
**Why?**
To support https://github.com/temporalio/temporal/pull/5868
`make proto` in temporal

Support --descriptor_set_in in protogen

---

.github/workflows/update-proto.yml

Reverts temporalio/api-go#116
Looks like something broke autoupdate of this repo when a change is merged in https://github.com/temporalio/api repo. This commit is a possible reason for the breakage. So reverting it to see if the updates go through.

Revert "Change update-proto workflow auth"

---

.github/workflows/update-proto.yml

- Update actions versions.
- Add optional input to update protos of a specific branch
- Use Github token instead of the secrets `COMMANDER_DATA_TOKEN`
- Fix bug when the commit message contains double-quotes.
**Why?**

Update GHA update-proto.yml

---

.github/workflows/update-proto.yml

The Github token cannot bypass required pull request, but the Temporal CICD app can, which I've added to the list of allowed users to bypass it.
**Why?**

[GHA] Replace token with CICD app

---

.github/workflows/ci.yml

- Bumped Go version used for CI builds to 1.21
**Why?**
- Our automated merge builds [began failing](https://github.com/temporalio/api-go/actions/runs/10604768987/job/29392179469)
- [gRPC release 1.66](https://github.com/grpc/grpc-go/tree/v1.66.0?tab=readme-ov-file), which the auto commit updated the package to, supports 1.22 and 1.23.  
- Pending

Bump Go version for CI builds to 1.22

---

cmd/proxygenerator/go.mod
cmd/proxygenerator/go.sum
cmd/proxygenerator/interceptor.go
proxy/interceptor.go
proxy/interceptor_test.go

Fixed issue during payload visiting where leftover parent mutated in nested calls was not reset. Closes https://github.com/temporalio/sdk-go/issues/1614.

Fix issue with parents not reset during payload visiting

---

Makefile

Previously we automatically updated all dependencies on every proto submodule update GitHub workflow (triggered by merge in `api` repo). This means that we are forcing users to upgrade things like gRPC unnecessarily. This removes that step from the proto submodule update.

Remove automatic dependency upgrade on proto update

---

cmd/proxygenerator/interceptor.go
proxy/interceptor.go
proxy/interceptor_test.go

* Added `WellKnownAnyVisitor` to `VisitPayloadsOptions` with default for visiting any
* Updated generator to make sure "Any" types are visited
Closes https://github.com/temporalio/sdk-go/issues/1622

Visit "Any" types in payload visitor

---

Makefile
cloud/cloudservicemock/v1/service_grpc.pb.mock.go
cmd/mockgen-fix/main.go
operatorservicemock/v1/service_grpc.pb.mock.go
workflowservicemock/v1/service_grpc.pb.mock.go

Mocks were generated for older gRPC versions that didn't have the requirement to embed the unimplemented server as they do now. So we make sure this properly does embed this unimplemented server there and assert we conform to the interface.
I do not believe this should be considered a 💥 backwards compat break because others embeds of this should still work.
Closes https://github.com/temporalio/sdk-go/issues/1628

Add unimplemented gRPC server embeds to mock servers

---

Makefile
cmd/proxygenerator/interceptor.go
proxy/interceptor.go

- Visit OperatorService methods in interceptor
- Reenable `generatorcheck` Makefile target
**Why?**
There are payloads in the Nexus EndpointSpec description that need to be visited for completeness.

Visit OperatorService methods in interceptor

---

cmd/proxygenerator/interceptor.go
proxy/interceptor.go
proxy/interceptor_test.go

Fixed a bug where the proxy visited single payload fields but didn't actually set the converted result on the parent object.

Fix proxy manipulation of single payload fields

---

.github/workflows/check-sdk-compat.yml

GHA check sdk-go compatibility
**Why?**
Automation: be able to check if a api-go version breaks sdk-go

GHA check sdk-go compatibility

---

.github/workflows/create-release.yml
.github/workflows/create-tag.yml
.github/workflows/delete-release.yml
.github/workflows/publish-release.yml

GHA to create, publish and delete releases.
The workflow can only be triggered by another workflow (from `api` repo).
**Why?**
Automation.

GHA to create release

---

.github/workflows/check-sdk-compat.yml

Set staticcheck config to ignore deprecated symbols check
**Why?**
API might introduce deprecated functions, and it should block this workflow for releasing the aPI.
Running the workflow without this change fails, and with this change passes when the API introduces deprecated functions.

[GHA][check-sdk-compat] Set staticcheck config to ignore deprecated symbols check

---

cmd/proxygenerator/interceptor.go
proxy/interceptor.go
proxy/interceptor_test.go

**What**
Add `update.Response` to proxy
**Why?**
Without this change payloads under `update.Response` are skipped by the proxy. This can cause update results to not go through the proxy.
New unit test added

Fix update.Response getting skipped by the proxy

---

cmd/proxygenerator/interceptor.go
proxy/interceptor_test.go

Add test for proxy to make sure all payloads are visited even if it's not reachable.
**Why?**
This uses a different approach than how our proxy codegen discovers things #210
Added new tests
Discovered a few gaps while writing this new test
[#1862](https://github.com/temporalio/sdk-go/issues/1862)
[#1864](https://github.com/temporalio/sdk-go/issues/1864)
[#1865](https://github.com/temporalio/sdk-go/issues/1865)
None, this is test-only changes

Add test for proxy to make sure all payloads are visited

---

cmd/proxygenerator/interceptor.go
proxy/interceptor.go
proxy/interceptor_test.go

Added support for payload and failure visitor to visit repeated Any fields.
Closes https://github.com/temporalio/sdk-go/issues/1864
**Why?**
Scenario we want to support
Added unit tests
entire payload/failure visitor breaks?

Add support for parsing and testing repeated any fields

---

cmd/proxygenerator/interceptor.go
proxy/interceptor.go
proxy/interceptor_test.go

Added support for repeated payload.
Also added a note in the `VisitPayloads` godoc mentioning how we don't support directly visiting payloads (see https://github.com/temporalio/api-go/pull/202#discussion_r1920352920 for context).
Closes https://github.com/temporalio/sdk-go/issues/1862 and can probably close https://github.com/temporalio/sdk-go/issues/1862 as well, now that the godoc mentions this scenario.
**Why?**
Support an edge case scenario, only [AggregationGroup](https://github.com/temporalio/api/blob/9156239c8272003b6f228951602ca2b130a55876/temporal/api/workflowservice/v1/request_response.proto#L938) today uses this.
Added tests

Support visiting repeated Payload

---

serviceerror/aborted.go
serviceerror/convert.go

Added `Aborted` serviceerror.
**Why?**
There's a need to return an `Aborted` serviceerror from the server.
Given that we these serviceerror types for each status code, it seems like the right thing to add this here.

Add "Aborted" servicerror
